name: ci

on:
  push:
    branches:
    - '*'
    - '*/*'
    - '**'

jobs:
  test:
    name: Compile & Test
    strategy:
      matrix:
        go-version: [1.24]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup and run integration tests
      run: make integration
